### ISSUE TITLE
New feature: projects overview page

### ISSUE THREAD

**Issue by scitronboy** [hackclub/summer-scrapbook#82]
I left a message in HQ an few weeks ago suggesting a new feature for scrapbook: A project-level overview of every user's project in scrapbook. Right now, scrapbook shows a feed of updates from each user. However, it's nothing more than that. I think it would be cool to have a page on scrapbook that has **one post** per user that has an image, title, and project description - like a portfolio of WIP SOM projects made by Hack Clubbers. This would be my first time contributing to the hc website so I'm laying out my plan below so you all can review it before I open a PR.

First, there would be a new page at `/projects` on the scrapbook which would have a similar layout to the homepage, except instead of a card for each update it would have a card for each user. I'm not yet sure how these would be sorted - perhaps randomly, or with users with the most recent posts first. Each card would consist of the project's title, the user's handle, a project description, and an optional project photo. Each card would link to the user's scrapbook page, as usual.

Each user's scrapbook page would also get the title and description of their project added to the top, below the streak chart and links.

Finally, there would be a new scrappy command `/setproject <title | description | image> ...` which users could use to change their project details. Users who don't set their project details will not be added to the portfolio.

I'm not familiar with Airtable but I'm guessing we would have to create a new table `ProjectsTable` which I could then access through airbridge using a new scrapbook API route.

So, does this sound good? Or is there anything I need to change or not do?

**Comment by sampoder** [comment]
Big +1

I remember actually reading your hq post, I made a mockup and thought of a similar user flow and sent them to Lachlan. Now I feel a bit more confident with Next etc. so I can help out here, I'm not Lachlan but I like the plan. I'll let them comment as well but if you'd like I can help out

one thing we could probably just tie this to the user record in Airtable instead of creating a new base

also thank you a million for such a detailed plan

<img width="1192" alt="Screenshot 2020-07-08 at 6 04 17 PM" src="https://user-images.githubusercontent.com/39828164/87898939-34e1e480-ca82-11ea-8248-842c6201e660.png">

**Comment by sampoder** [comment]
Also our sincere apologies, for never responding to your post.

**Comment by lachlanjc** [comment]
Hey @scitronboy, thanks so much for the detailed write-up here. I’ve had some conversations with the team today & done some thinking about this, and I think the main thing is: however we proceed, I want it to be very throughly thought-out, and feel totally Scrapbook-y. Personally, I totally get what you’re going for here, but I am extremely hesitant to add another concept to Scrapbook—right now, it’s super simple, people make posts, and those posts can be reacted to and that tags them. Other features, like mentions, are very much sub-capabilities of “people make posts,” & don’t add a lot of conceptual weight to understanding how to use Scrapbook. At least personally, I think the features we’ve added so far—mentions, reactions, webrings, CSS/audio—each extend the core dynamic of Scrapbook without complicating its basic interactions, but augmenting them for more engaged folks. Keeping them all feeling very lightweight & [fast](https://craigmod.com/essays/fast_software/ ) has been critical. The edges are very clear: the social network part of Scrapbook is the Slack channel, the website is an explorable, interlinked portfolio of Hack Clubbers’ days.

Projects, while they seem simple from the outside, I think are different here since they’re adding a second interaction to Scrapbook, beyond “people make posts,” to “people make posts and projects,” and then posts are part of projects but projects can also exist on their own, several people can theoretically work on a project or else there are variants of the same project for each collaborator (like Hackagotchi or something). That’s a *lot* of conceptual weight & like a dozen interaction paths to fully think through (create project, tag post as project, untag post as project, delete project, edit project, share project, view all projects, view projects on profiles, see project on posts on homepage & profile, there are more). Right now, I don’t think such a direct implementation is quite the right move.

So I think this leaves us with a few options.

1. Leverage the existing reactions. We could 1) allow you to show reactions on your profile & 2) allow filtering your posts on a profile by project. You could create an emoji for your project, then several people could use it & the existing reaction pages would show all the posts for it, or you could just use it yourself & filter those posts on your profile.
2. Skip projects entirely, but preserve the presentation on your profile as your top post, with a pinned post. React *to your own post* with a pin emoji on Slack, then the latest one would always show up as your top post. The idea is you’d describe your project(s) with just a regular Scrapbook post, but have it pinned. The pin reaction page would show everyone’s pinned posts, which is kind of cool. This would be pretty straightforward to implement. It’d feel a lot like pinned tweets.
3. Create something for projects that’s super lightweight, like writing your project name in backticks at the beginning of your posts, then we’d be turning those into some kind of indicators on the site. I never want creative interactions you have with Scrapbook to be not public on Slack, and this would preserve posts on Slack containing all the relevant metadata. The red code text on Slack kind of looks like a tag, too. But there’s a lot of technical & design complexity to this.

Personally, I think I’m going to keep sitting on this & figuring out the best way forward. I like the pinned posts, but at the same time, I’m not sure that I’d use the feature or what I’d use it for. I’m interested to hear your thoughts!

**Comment by scitronboy** [comment]
OK! I honestly came up with my idea with the goal of increasing the usability of the scrapbook website for non-members, or people who are visiting the site without necessarily knowing what everyone's working on. I get that the scrapbook was mostly designed as in internal website to augment interactions and posts in the #scrapbook channel. However, in my opinion, as scrapbook is like the face of Hack Club's summer of making in a way (it's on the hack club homepage, and many members link to their scrapbooks from their websites, etc.) I think adding portfolio/project functionality would be a great opportunity to showcase what everyone's making - with short synopses instead of a series of updates. 

Also - my idea for projects was originally more just a way to improve the profile pages with an **optional** short description and title set with a Scrappy command. This would mostly be just extending the core functionality. However, this is likely the same information that people are already sharing on their websites or github profiles or twitters, so maybe it would be redundant. And my idea for the portfolio/project page was originally just to combine all the projects/profiles from Hack Clubbers together on one page (**one project per member**), as is already done on the regular Scrapbook page. The project info shown on this page would be the same as the info members have set for their profile/scrapbook page. You raise good points about complexity becoming a problem, though - I forgot that some people are collaborating on projects, which could lead to duplicate project listings.

Again, I'd like to emphasize that my idea wasn't to add a new type of post, but rather a.) a new optional profile page feature (like webrings) and/or b.) a new overview page in addition to the current one.

I like the ideas you mentioned, but as you said, I'm not sure I'd use them. I definitely wouldn't want to type a project name in backticks on _every_ post. And the pin idea sounds like a good way to add a description to your profile using the same features (posts, reactions) that are already being used (I think my idea would be more user-friendly for site visitors, but that's clearly a biased opinion).

Finally, one problem with my idea that's occurred to me is the whole process vs. product problem, and how one of the fundamental purposes of scrapbook is to highlight the process everyone's going through to make their product (struggles, checkpoints, ideas, etc). Adding a feature that focuses on the product, or end-goal of each user's project, might take some focus away from the process (which could lead to demotivation, etc.), but this is just a guess and might not actually become a problem.

Thanks for your thoughts, and please correct me if I'm wrong about any of the above. I'll keep thinking about this as well, but if you reach a decision about adding some sort of project/portfolio functionality let me know so I can help implement it :smiley:

**Comment by lachlanjc** [comment]
I’m closing this since we’re not planning on building significant new features for Scrapbook anymore. Thank you so much for the detailed ideas & writeup—super appreciate it.
